name: python-slacker

on:
    schedule:
      - cron: '0 0 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests BeautifulSoup Slacker
    - name: Run main.py
      run: |
        python main.py
      env:
        SECURE : ${{ secrets.PYTHON_SLACKER }}
