name: python-slacker

on:
    schedule:
      - cron: '00 23 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 Slacker
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main.py
      working-directory: ./식단_자동화
      run: |
        python main.py
      env:
        SECURE : ${{ secrets.PYTHON_SLACKER }}
