name: python-hydro

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main.py
      working-directory: ./hydrothermal_energy
      run: |
        python main.py
      env:
        SECURE : ${{ secrets.PYTHON_HYDRO }}

